### ISSUE TITLE
relative paths are broken

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#116]
running mrdox-test using relative path arguments does not work

**Comment by klemens-morgenstern** [comment]
Do you have more details? What's the error, which arguments?

**Comment by vinniefalco** [comment]
mrdox channel has a discussion from today with @vinniefalco and @Ukilele .

We need to research if relative paths are ever possible in compile_commands.json. If not, then we should convert relative path arguments to full paths (using the current directory, I have some code in mrdox that does this already).

We might add "makeFullPath" to source/Support/Path.hpp as a utility function.

**Comment by vinniefalco** [comment]
This should work now
