### ISSUE TITLE
The high-level usage of the tool should be 2-step

### ISSUE THREAD

**Issue by grisumbras** [cppalliance/mrdox#12]
The tool should be used similarly to C and C++ compilers: one invocation converts source to data, another invocation should assemble final result from data files created on step 1. This model is what build systems fundamentally support and hence no tfollowing it results in worse experience.

Consider a project with many files. If aforementioned 2-step model is not used, when a single file is changed than every source file has to be processed again. Even if the tool implements optimisation where it checks if a source file has been changed after the target was created, first of all it has to get a piece of information that was already available to the build system. But secondly, a C++ source file does not has to be itself for its contents to effectively change. Any of the headers it includes can effect such a change. So, the tool would have to recursively check all headers the file includes if they have been changec too. This work is already being done by build systems, it would be wasteful to implement it again and repeat it at runtime. And finally, a build system may have a different idea what "file has changed" means, for example Scons checks a file's hash rather then checking its last edit timestamp. Presumably, Scons users prefer or at least expect that semantics for "file has changed" rather than the one implemented inside mrdox.

In addition, there's an additional benefit to 2-step approach by itself. If the data format (currently XML) is documented, then other tools could be used to process it.

**Comment by vinniefalco** [comment]
No thanks

**Comment by vinniefalco** [comment]
The idea of only rebuilding what is needed has merit but it needs to be opened as a separate issue
