### ISSUE TITLE
Installer / Package Built Action

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#139]
To help people use MrDox without the need to build LLVM, we could have GHA scripts to build packages for Linux or however that works, plus installers for Windows and MacOS. These would be published as a Release archive in GitHub.

**Comment by klemens-morgenstern** [comment]
Will need some work, but CPack sound like a possibly candidate - should we provide repositories for yum or apt, too?

**Comment by vinniefalco** [comment]
How could I possibly know? All I can tell you is I would like a signed Windows installer (I guess its called .msi or something like that but I am not 100% sure).
