### ISSUE TITLE
ditch thread_local

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#144]
Seems to always cause problems, now a crash on exit in debug builds on msvc

**Comment by klemens-morgenstern** [comment]
All `thread_local` is currently used for is for micro-optimizations of string allocations. I'd just remove all of them, libc will buffer allocations.

**Comment by vinniefalco** [comment]
Yep lets do that.

**Comment by vinniefalco** [comment]
The time for that shit is after we have a release and we are using a profiler, not during development. My fault.

**Comment by vinniefalco** [comment]
The thread locals are gone.
