### ISSUE TITLE
read .git/config

### ISSUE THREAD

**Issue by klemens-morgenstern** [cppalliance/mrdox#18]
Possibly way to get the repo Url. E.g.:

```ini
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:klemens-morgenstern/async.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "pages"]
	remote = origin
	merge = refs/heads/pages
```

**Comment by vinniefalco** [comment]
What is this?

**Comment by klemens-morgenstern** [comment]
a `.git/config` file from one of my projects.

**Comment by vinniefalco** [comment]
but what's the purpose of this? mrdox should read the file?

**Comment by klemens-morgenstern** [comment]
mrdox could read this to get the remote url

**Comment by vinniefalco** [comment]
Well even that might not be correct - the remote URL could point to the user's fork instead of the authoritative upstream. No, nothing in .git can help us.
