### ISSUE TITLE
Decompose compound types

### ISSUE THREAD

**Issue by sdkrystian** [cppalliance/mrdox#209]
Consider the following:
```
struct S { };

S x;
S* y;
```
which produces the following output:
```
<namespace name="">
  <struct name="S" id="pOYGF6pLJlICuiGO0Xj0daDb/to=">
    <file path="input.cpp" line="6" class="def"/>
  </struct>
  <variable name="y" id="cND4SpNe0NdSmFwUXrBAZmL6sLo=">
    <file path="input.cpp" line="9" class="def"/>
    <type name="S *"/>
  </variable>
  <variable name="x" id="ujOvtFFNPf6akih2fga4S9j6Y9M=">
    <file path="input.cpp" line="8" class="def"/>
    <type name="S" id="pOYGF6pLJlICuiGO0Xj0daDb/to="/>
  </variable>
</namespace>
```
It may be desirable to define types (i.e, `TypeInfo`) in a way that separates cv-qualifiers and (pointer/reference/array/function)ness from the unadorned types (so their IDs can be used to reference the declaration of the type).

**Comment by vinniefalco** [comment]
Well the rationale in the original clang-doc is that this would produce an explosion of small allocated TypeInfos. And how does separating the cv-qualifiers help the documentation?

**Comment by sdkrystian** [comment]
@vinniefalco look at https://clang.llvm.org/doxygen/classclang_1_1ASTContext.html#aa39dff434d30711957097bb5b9d04343 -- note how there is a link to `ArrayType` in the return type, even though it is a pointer to a cv-qualified type
