### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by VWY-github** [cppalliance/mrdox#219]
Attempting to build on ubuntu 22.04 using clang Version 15 with source latest commit 9d909e3 today May 27.
My compile script:
[buildMrDox.txt](https://github.com/cppalliance/mrdox/files/11582433/buildMrDox.txt)

The error output is all about std::optional here
[output.txt](https://github.com/cppalliance/mrdox/files/11582441/output.txt)

**Comment by sdkrystian** [comment]
Oops. That header won't be around much longer, so it will be fixed when #211 is merged
