### ISSUE TITLE
Get CI warnings under control

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#249]
Often I see warnings and such in the CI logs:

![image](https://github.com/cppalliance/mrdox/assets/1503976/15e34143-d1c9-4d11-aa0f-dbf60b37c75e)

they disappear, then come back, etc. We need to solve this once and for all.

**Comment by sdkrystian** [comment]
@vinniefalco I believe the warnings you are referring to were the "unrecognized flag" warnings in the GCC CI for the reference.adoc/reference.xml generation tests; the offending flags are being passed by https://github.com/cppalliance/mrdox/blob/develop/CMakeLists.txt#L169

**Comment by sdkrystian** [comment]
194dcca fixes the warnings you included in the issue
