### ISSUE TITLE
Odd msvc warning now about /W4

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#251]
```
>------ Build started: Project: CMakeLists, Configuration: Debug ------
  MSBuild version 17.5.1+f6fdcf537 for .NET Framework
  
    Checking File Globs
    Checking Build System
    Building Custom Rule C:/Users/Vinnie/src/mrdox/CMakeLists.txt
C:\Users\Vinnie\src\mrdox\build\cmake-msvc\DebugWithRel\cl : command line warning D9025: overriding '/W4' with '/w' 
```

**Comment by sdkrystian** [comment]
`include(HandleLLVMOptions)` is what adds all the non-target specific compile flags (including `/W4`), which conflicts with the `/w` flag used for duktape.

**Comment by alandefreitas** [comment]
> non-target specific compile flags

Oh... I hate these. `/w` is private even. 

I think there's a way to use LLVM with this module but I don't remember how.

I guess we can fix this simply by finding LLVM last though.

**Comment by alandefreitas** [comment]
I tried importing LLVM after all other dependencies but the error is still there.

https://github.com/alandefreitas/mrdox/actions/runs/5197321858/jobs/9372010104#step:6:1295

I think the only solution here is to find another way to consume LLVM without these scripts that define global requirements.
