### ISSUE TITLE
Implement `SingleFileDB` using `AbsoluteCompilationDatabase`

### ISSUE THREAD

**Issue by sdkrystian** [cppalliance/mrdox#379]
Right now they lack feature parity (e.g. the ability to specify predefined macros), and we don't want to reimplement each option twice.

**Comment by vinniefalco** [comment]
I already have this in my branch now so I will take it

**Comment by vinniefalco** [comment]
oh this is merged already...
https://github.com/cppalliance/mrdox/blob/123a575ef20a138a0580e8b7b169072a4bf7ea04/test/TestRunner.cpp#L122
