### ISSUE TITLE
Automated build and deployment of demo documentation

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#402]
To showcase this product to stakeholders, we need GitHub actions to build and publish reference documentation in a variety of formats for select code bases (I am using Boost.URL as an example but it could be any library that is javadoc-rich). We envision these published URLs:

https://mrdox.com/master/demo/boost-url/adoc-single
https://mrdox.com/master/demo/boost-url/adoc
https://mrdox.com/master/demo/boost-url/xml
https://mrdox.com/master/demo/boost-url/html-single
https://mrdox.com/master/demo/boost-url/html

https://mrdox.com/develop/demo/boost-url/adoc-single
https://mrdox.com/develop/demo/boost-url/adoc
https://mrdox.com/develop/demo/boost-url/xml
https://mrdox.com/develop/demo/boost-url/html-single
https://mrdox.com/develop/demo/boost-url/html

"single" is the single-page output format, otherwise it is multipage. New docs should be built every time there is a change to develop or master, and if we could watch the URL repo that would be nice too. Please put the necessary files such as the mrdox.yml in the URL repo.

Start by manually uploading all the "develop" generated reference documentation so we can have a starting point.

**Comment by alandefreitas** [comment]
@sdkrystian I can't do that without your help. We'll have to coordinate on this.

**Comment by sdarwin** [comment]
The website https://mrdox.com/ has been set up as an nginx proxy.   
Upload or sync files to a directory in s3.  
Don't sync the entire bucket, only one directory.  

```
aws s3 cp --region us-west-2 --recursive ___  s3://cppalliance-ci/mrdox.com/
```
