### ISSUE TITLE
no fetchcontent

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#405]
No CMakeLists.txt anywhere in Boost or CPPAlliance should require the Internet to execute.

**Comment by alandefreitas** [comment]
I think this fixes itself when duktape is removed.

**Comment by vinniefalco** [comment]
> I think this fixes itself when duktape is removed.

1. I'm not removing duktape, and
2. I want it removed from all CMakeLists.txt for any of our projects (URL, JSON, Beast, http-proto, http-io, buffers, mrdox, handlebars, static-string)

I am so sick of Visual Studio hanging for 5 minutes where I have no control

**Comment by alandefreitas** [comment]
> I'm not removing duktape, and

Yes. I already fixed that in a PR I'm opening soon in any case.

> I want it removed from all CMakeLists.txt for any of our projects (URL, JSON, Beast, http-proto, http-io, buffers, mrdox, handlebars, static-string)

There's no fetch content in any other library. Any other problem your having is unrelated to this.
