### ISSUE TITLE
Are data members indexed and do they need USRs?

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#42]
Currently, data members of records are not inherited from `SymbolInfo`. That means there is no source location information and no USR, so these items cannot be indexed, hyperlinked, or have source information displayed.

**Comment by vinniefalco** [comment]
Data members are indexed in `MemberTypeInfo`. Not static ones though (those are `VarDecl`. Those member metadata structs need work...

**Comment by sdkrystian** [comment]
Non-static data members use `FieldInfo`, static data members use `VariableInfo`. Both are derived from `Info` and have `SymbolID`s.
