### ISSUE TITLE
Dependencies should be pulled in using a package manager

### ISSUE THREAD

**Issue by Tsche** [cppalliance/mrdox#56]
Please evaluate if a package manager such as Conan (preferably) or VCPKG can be used to pull in required dependencies. That would significantly simplify the build process.

**Comment by vinniefalco** [comment]
idk about conan but vcpkg only has an older llvm. Hopefully no one will be having to build mrdox except package managers, as it should come prebuilt.

**Comment by vinniefalco** [comment]
I'm going to close this because it is out of scope. If you want to build MrDox you have to install LLVM and/or build LLVM. How you do that is up to you.
