### ISSUE TITLE
Remap AccessSpecifier in bitstream

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/mrdox#84]
`AccessSpecifier::AS_public` is zero, and zero values are stripped out of bitstream output. It would be better if the number zero represented "no access specifier." We can do this by creating our own mapping of AccessSpecifier to bitstream RecordID when reading and writing bitcode. At the same time we should normalize the field so there is only one record ID instead of multiple, and we should relax the abbreviation builder so that it allows the same record ID to appear in more than one abbreviation.

**Comment by sdkrystian** [comment]
`AccessSpecifier` maps to `AccessKind`. `AccessKind::Public` has the value `0` because it is the most common.
